# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yousefs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: example-todo-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::396913740002:role/lecture-role

build:
  esbuild:
    minify: true


package:
  individually: true

functions:
  GetTodo:
    handler: functions/GetTodo/index.handler
    events:
      - httpApi:
          path: /todos
          method: get
  PostTodo:
    handler: functions/PostTodo/index.handler
    events:
      - httpApi:
          path: /todos
          method: post
  UpdateTodo:
    handler: functions/UpdateTodo/index.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: put

resources:
  Resources:
    MyTodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: example-todos3
        AttributeDefinitions:
          - AttributeName: "todoId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "todoId"
            KeyType: HASH # Primary key (partition key)
        BillingMode: PAY_PER_REQUEST