# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yousefs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: example-todo-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::396913740002:role/lecture-role

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  GetTodo:
    handler: functions/GetTodo/index.handler
    events:
      - httpApi:
          path: /todos/{username}
          method: get
  PostTodo:
    handler: functions/PostTodo/index.handler
    events:
      - httpApi:
          path: /todos
          method: post
  UpdateTodo:
    handler: functions/UpdateTodo/index.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: put


  GetRecent:
    handler: functions/GetRecent/index.handler
    events:
      - httpApi:
          path: /todos/recent
          method: post

resources:
  Resources:
    MyTodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: new-example-todos
        AttributeDefinitions:
          - AttributeName: "username"
            AttributeType: "S"
          - AttributeName: "todoId"
            AttributeType: "S"
          - AttributeName: "timestamp"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "username"
            KeyType: HASH # Partition key
          - AttributeName: "todoId"
            KeyType: RANGE # Sort key
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: timestampIndex
            KeySchema:
              - AttributeName: "timestamp"
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: usernameIndex
            KeySchema:
              - AttributeName: "username"
                KeyType: HASH
            Projection:
              ProjectionType: ALL
