# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yousefs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dynamo-exempel
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
 region: eu-north-1
  iam:
  role: arn:aws:iam::396913740002:role/lecture-role






  plugins:
  - serverless-webpack


  package:
  individually: true


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
